server {
    listen       80;
    server_name  localhost;
    client_max_body_size 2048m;

   
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm index.shtml;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location /${APP_NAME} {
        alias /usr/share/nginx/html/;
        index  index.html index.htm index.shtml;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    error_page  405 =200 $uri;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}